### ISSUE TITLE
 * failed to add service - already in use? when using dtoverlay=vc4-fkms-v3d

### ISSUE THREAD

**Issue by rubenverhoef** [meekys/cam_overlay#12]
I get :
` * failed to add service - already in use?`
when i'm using `dtoverlay=vc4-fkms-v3d` in my config.txt on my RPI
Any ideas?

**Comment by meekys** [comment]
Hi @rubenverhoef ,

This looks like this might not be compatible with the display method that cam_overlay uses, dispmanx overlay and gles

https://www.raspberrypi.org/forums/viewtopic.php?t=159853
> The standard camera and video decode apps that drive the display from the gpu cannot be used when vc4-kms-v3d is enabled.
Apps that use dispmanx for overlays or performance reasons (e.g. emulators) cannot be used.

If you're using X11, you could try compiling it in that mode?
`make clean && make DISPLAY=x11`

**Comment by rubenverhoef** [comment]
Okay i will try and see what the performance and usability are.
