### ISSUE TITLE
Possible to add option without guidelines

### ISSUE THREAD

**Issue by Bishamon1987** [meekys/cam_overlay#16]
Hey,
I have Crankshaft NG running on my pi 3B+.
I want to add a front and back camera. 
I will use a switch to change the views. 
Pressing forward is front cam. Middle stand is camera off. Pulling backwards is rearcam.
I dont need any guidlines for the front view. But i need them for the back. 
Is it possible to make a option for this?
Thanks

**Comment by meekys** [comment]
@Bishamon1987 Sure, that should be possible as a new feature.
For now, a workaround would be simply to edit the overlay.png and make it all transparent.

**Comment by Bishamon1987** [comment]
Maybe an even better solution would be this:
option for which guideline.png to use.

I have two camera's, front and rear. So I need different images for each. Since the height and vertical angles are different.

**Comment by meekys** [comment]
Added option to specify an overlay file. -O or --overlay, with a default of res/Overlay.png
Must be a relative path to cam_overlay.bin

**Comment by Bishamon1987** [comment]
That's great! Now I have to directories with camoverlay.
One called rearcam and other called frontcam
