### ISSUE TITLE
Failed to add service

### ISSUE THREAD

**Issue by TheFuzz4** [meekys/cam_overlay#3]
Good evening,

First off thank you for this project as I am certain this will make my OpenAuto experience just amazing.  I purchased a USB camera to use with my pi.  I've tested this camera out on my regular Ubuntu box and confirmed it does play well with linux.  I've also tested it out with vlc on the pi as well and all is good.  However when I fire off the command to start the cam_overlay it throws the following error.  I've tried it both as pi and also as root with the same results.  I also attempted to compile it as myself and as root as well with the same results.  I'm not sure what service its attempting to add here.  Thank you very much for your help and for writing the perfect reverse cam app. 

`Opened device '/dev/video0'
Dimensions: 800 x 600 Pixel Format: YUYV
* failed to add service - already in use?
`

**Comment by TheFuzz4** [comment]
BTW I solved this tonight.  It turns out that I had the Open GL enabled.  I'm using OpenAuto Pro.  I disabled the OpenGL and all is right in the world.

**Comment by andreimoraru** [comment]
@TheFuzz4 I confirm that disabling OpenGL fixed the error for me as well.

OpenAuto Pro 2.0
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

Steps to fix:
1) Run **raspi-config** in Raspbian shell.
2) Go to **Advanced Options**
3) Go to **A7 GL Driver**
4) Select **G3 Legacy Original non-GL desktop driver.**
5) Choose **Ok** then **Finish**. 
A reboot will be required.

Next, run ./cam_overlay with appropriate parameters for your setup.

**Comment by egisz** [comment]
Hi, 
I get same error even with disabled OpenGL, running RPI4.
What rpi do you use? 
What branch: master or cpp?
