### ISSUE TITLE
Need to add info to readme on how to exit cam_overlay

### ISSUE THREAD

**Issue by jonlowe** [meekys/cam_overlay#6]
The only way I've found to stop cam_overlay once running from the command line is to physically pull the USB plug.  I've tried a variety of commands, etc, but nothing works.Obviously pulling the plug isn't practical in a car. A description of how to kill the program needs to be added to the readme.

**Comment by meekys** [comment]
Instructions have now been added.
For summary:
- Ctrl+C
- killall cam_overlay.bin
- Sending SIGTERM programmatically

**Comment by jonlowe** [comment]
Thanks!
